[package]
name = "simd-ruler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[[bench]]
name = "simd"
harness = false

[[test]]
name = "length"

[dependencies]
wide = { version = "0.7.33", default-features = false }
libm = { version = "0.2", default-features = false, features = ["arch"] }

[dev-dependencies]
geo-ruler = { workspace = true, default-features = true }
criterion = "0.5.1"
approx = "0.5.1"

[features]
default = ["std"]
std = ["wide/std"]
